import { PropiedadDTO } from '@/app/shared/domain/shared.domain';

export const FORM_PROPERTIES = {
  TERCERO: 'TERCERO',
  ENCABEZADO: 'ENCABEZADO',
  DESCRIPCION: 'DESCRIPCION',
  DESCRIPCION_NIVEL2: 'DESCRIPCION_NIVEL2',
  SUBTOTAL: 'SUBTOTAL',
  TOTAL: 'TOTAL',
  TOTAL_FUNCION: 'TOTAL_FUNCION',
  CONSECUTIVO: 'CONSECUTIVO',
  FECHA: 'FECHA',
  RESPONSABLE: 'RESPONSABLE',
  ORDEN: 'ORDEN',
  AYUDA: 'AYUDA',
  SOLICITAR_FECHAS: 'SOLICITAR_FECHAS',
  ANULAR: 'PLANTILLA_ANULAR',
  ACTIVATE: 'PLANTILLA_ACTIVAR',
  COPY_TEXT: 'COPY_TEXT',
  FORMATO: 'FORMATO',
} as const;

export const PERMISSION_PROPERTIES = {
  PLANTILLA_CREAR: 'PERMISO_PLANTILLA_CREAR',
  PLANTILLA_MODIFICAR: 'PERMISO_PLANTILLA_MODIFICAR',
  PLANTILLA_INICIO_RAPIDO: 'PERMISO_PLANTILLA_INICIO_RAPIDO',
  PLANTILLA_CARGA_MASIVA: 'PERMISO_PLANTILLA_CARGA_MASIVA',
  PLANTILLA_CARGA_MASIVA_MULTIPLE: 'PLANTILLA_CARGA_MASIVA_MULTIPLE',
  PLANTILLA_TIPO_CONFIGURATION: 'PLANTILLA_TIPO_CONFIGURATION',
  PLANTILLA_CAMBIAR_ESTADO: 'PERMISO_PLANTILLA_CAMBIAR_ESTADO',
  PLANTILLA_TRANSFERIR: 'PERMISO_PLANTILLA_TRANSFERIR',
  PLANTILLA_LISTAR_MENU: 'PERMISO_PLANTILLA_LISTAR_MENU',
  CAMPO_BLOQUEAR: 'PERMISO_CAMPO_BLOQUEAR',
  CAMPO_MODIFICABLE: 'PERMISO_CAMPO_MODIFICABLE',
  CAMPO_OPCIONAL: 'PERMISO_CAMPO_OPCIONAL',
  CAMPO_RENDER: 'PERMISO_CAMPO_RENDER',
} as const;

export const TEMPLATE_PROPERTIES = {
  OCULTAR_GUARDAR: 'PLANTILLA_OCULTAR_GUARDAR',
  INSTRUCCION_CREAR: 'PLANTILLA_INSTRUCCION_CREAR',
  HISTORIAL_ACTIVO: 'PLANTILLA_HISTORIAL_ACTIVO',
  INICIA_PROCESO: 'PLANTILLA_INICIA_PROCESO',
  HTML_DOCUMENT_SQL: 'HTML_DOCUMENT_SQL',
  TIPO_PRODUCTO: 'PLANTILLA_TIPO_PRODUCTO',
  TIPO_REPORTE: 'PLANTILLA_TIPO_REPORTE',
  TIPO_ROL: 'PLANTILLA_TIPO_ROL',
  SUCCESS_INFORMATION: 'PLANTILLA_SUCCESS_INFORMATION',
  VOUCHER: 'TEMPLATE_VOUCHER',
  ACCESO_RAPIDO: 'PLANTILLA_ACCESO_RAPIDO',
  NUEVO_USUARIO: 'PLANTILLA_NUEVO_USUARIO',
  LOGIN_HTML: 'LOGIN_HTML',
} as const;

export const FIELD_TYPE_PROPERTIES = {
  ROL: 'ROL',
  FUNCION_VALIDAR: 'FUNCION_VALIDAR',
  MODIFICABLE: 'MODIFICABLE',
  COLOR: 'COLOR',
  APP_DFA: 'APP_DFA',
  PRODUCTO_CAMPO_VALOR_MINIMO: 'PRODUCTO_CAMPO_VALOR_MINIMO',
  PRODUCTO_CAMPO_VALOR_UNITARIO: 'PRODUCTO_CAMPO_VALOR_UNITARIO',
  PRODUCTO_CAMPO_CANTIDAD: 'PRODUCTO_CAMPO_CANTIDAD',
  PRODUCTO_CAMPO_TOTAL: 'PRODUCTO_CAMPO_TOTAL',
  BUSQUEDA_SIN_TEXTO: 'BUSQUEDA_SIN_TEXTO',
} as const;

export const FIELD_BEHAVIOR_PROPERTIES = {
  DEFAULT: 'DEFAULT',
  TEXTO_LARGO: 'BASICA',
  TEXTO_FORMULA: 'TEXTO_FORMULA',
  DEPENDE: 'DEPENDE',
  PLANTILLA_AUXILIAR: 'PLANTILLA_AUXILIAR',
  CAMPO_HEREDADO: 'CAMPO_HEREDADO',
  ALERTAR_CAMPO_PROCESO: 'ALERTAR_CAMPO_PROCESO',
  MULTIPLE: 'MULTIPLE',
  INVISIBLE: 'INVISIBLE',
  VISIBLE_VALOR_DEPENDIENTE: 'VISIBLE_VALOR_DEPENDIENTE',
  AUTOLOAD: 'AUTOLOAD',
  READ_QR: 'READ_QR',
  LINK_EXTERNO: 'LINK_EXTERNO',
  SAVE_TO_SELECT: 'SAVE_TO_SELECT',
  INFORMATIVE_DATA: 'INFORMATIVE_DATA',
  UPDATE_INFORMATIVE_FIELD: 'UPDATE_INFORMATIVE_FIELD',
} as const;

export const FILE_PROPERTIES = {
  ARCHIVO_TIPO: 'ARCHIVO_TIPO',
  ARCHIVO_TAMANO_MAXIMO: 'ARCHIVO_TAMANO_MAXIMO',
  PORCENTAJE_CALIDAD: 'PORCENTAJE_CALIDAD',
  MULTIPLE_FILE: 'MULTIPLE_FILE',
  ARCHIVO_URL_USUARIO: 'ARCHIVO_URL_USUARIO',
  VALIDATE_ORIENTATION: 'VALIDATE_ORIENTATION',
  ARCHIVO_FIRMA: 'ARCHIVO_FIRMA',
} as const;

export const SQL_PROPERTIES = {
  PROCESO_FUNCION_SQL: 'PROCESO_FUNCION_SQL',
  FUNCION_SQL_NEW_ANTES: 'FUNCION_SQL_NEW_ANTES',
  SECCION_FUNCION_SQL: 'SECCION_FUNCION_SQL',
} as const;

export const NOTIFICATION_PROPERTIES = {
  FORCE_NOTIFICATION: 'FORCE_NOTIFICATION',
  FECHA_CON_HORA: 'FECHA_CON_HORA',
  FECHA_SIN_CALENDAR: 'FECHA_SIN_CALENDAR',
  FECHA_RANGO: 'FECHA_RANGO',
  FECHA_TIMER_BACK: 'FECHA_TIMER_BACK',
  FECHA_FUNCION_SQL: 'FECHA_FUNCION_SQL',
} as const;

export const BINARY_PROPERTIES = {
  VERDADERO: 'BINARIO_VERDADERO',
  FALSO: 'BINARIO_FALSO',
  PREGUNTA: 'BINARIO_PREGUNTA',
} as const;

export const NUMBER_PROPERTIES = {
  NUMERO_FORMULA: 'NUMERO_FORMULA',
  NUMERO_MAXIMO: 'NUMERO_MAXIMO',
  NUMERO_MINIMO: 'NUMERO_MINIMO',
  NUMERO_FUNCION_SQL: 'NUMERO_FUNCION_SQL',
  NUMERO_REDONDEO: 'NUMERO_REDONDEO',
  NUMERO_STEP: 'NUMERO_STEP',
  UNICO_PRODUCTO: 'UNICO_PRODUCTO',
  DETALLE_TARIFA_PRODUCTO: 'DETALLE_TARIFA_PRODUCTO',
  DETALLE_OCULTAR_UNIDADES_NOMBRE_CANTIDAD: 'DETALLE_OCULTAR_UNIDADES_NOMBRE_CANTIDAD',
  DETALLE_TARIFARIO_SQL: 'DETALLE_TARIFARIO_SQL',
  ITEM_DETAIL_FORM_VISIBLE: 'ITEM_DETAIL_FORM_VISIBLE',
  CONFIGURACION_OPCIONES: 'CONFIGURACION_OPCIONES',
} as const;

export const PROCESS_PROPERTIES = {
  POP: 'PROCESO_POP',
  ACCIONES: 'PROCESO_ACCIONES',
  VALOR: 'PROCESO_VALOR',
  BODEGA_MOVIMIENTO: 'BODEGA_MOVIMIENTO',
} as const;

export const REPORT_PROPERTIES = {
  VISIBLE_STATE: 'REP_VISIBLE_STATE',
  AUTOPRINT: 'REP_AUTOPRINT',
  MODULE_REFERENCE: 'REPORT_MODULE_REFERENCE',
} as const;

export const COVERAGE_PROPERTIES = {
  IMAGE: 'COVERAGE_IMAGE',
  TEMPLATE: 'COVERAGE_TEMPLATE',
  LAYOUT_APP: 'LAYOUT_APP',
  LANDING_PAGE: 'LANDING_PAGE',
  HEADER_PAGE: 'HEADER_PAGE',
  PUBLIC_USER: 'PUBLIC_USER',
} as const;

export const DATE_PROPERTIES = {
  MAXIMA_CAMPO: 'FECHA_MAXIMA_CAMPO',
  MINIMA_CAMPO: 'FECHA_MINIMA_CAMPO',
  MINIMA: 'FECHA_MINIMA',
  MAXIMA: 'FECHA_MAXIMA',
} as const;

export const LINK_PROPERTIES = {
  VINCULO_DATA: 'VINCULO_DATA',
  TRANSICION_VISIBLE_VINCULO: 'TRANSICION_VISIBLE_VINCULO',
  MODIFICAR_CAMPO: 'MODIFICAR_CAMPO',
  RELACIONAR_DOCUMENTOS: 'RELACIONAR_DOCUMENTOS',
  RETIRAR_DOCUMENTOS: 'RETIRAR_DOCUMENTOS',
} as const;

export const APP_PROPERTIES = {
  ADMIN: 'APP_ADMIN',
  READER: 'APP_READER',
  MODULES: 'APP_MODULES',
} as const;

export const DEPENDENT_PROPERTIES = [
  FIELD_BEHAVIOR_PROPERTIES.DEPENDE,
  LINK_PROPERTIES.MODIFICAR_CAMPO,
  FIELD_BEHAVIOR_PROPERTIES.INFORMATIVE_DATA,
  FIELD_BEHAVIOR_PROPERTIES.UPDATE_INFORMATIVE_FIELD,
  DATE_PROPERTIES.MAXIMA_CAMPO,
  DATE_PROPERTIES.MINIMA_CAMPO,
];
